[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
fs_permissions = [
  { access = "read", path = "." },
  { access = "write", path = ".env" },
  { access = "write", path = "../web/.env" }
]

# Compiler settings
solc = "0.8.27"
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
